[package]
name = "grid_wfc"
version = "0.1.0"
edition = "2021"

[dependencies]
core_wfc = { path = "../core_wfc" }
bevy = "0.11"
crossbeam = "0.8"
rand = { version = "0.8", features = ["small_rng"] }
serde = "1.0"
serde-xml-rs = "0.6"
anyhow = "1.0"
image = "0.24"
